from time import sleep


print('Welcome to the kitchen')
sleep(3)
print('In a freak accident, you shrunk yourself to the size of a paperclip')
sleep(3)
print('Now you must work your way through the kitchen to find the serum that will get you back to normal size')
sleep(3)
print('But beware, there are many obstacles in your way that could kill you')
sleep(3)

opt1 = input('You are standing on the kitchen counter, go ahead to the end of the counter (n) or jump off the side onto the floor (w)')
if opt1 == 'n':
    sleep(3)
    print('You go forward when suddenly, a knife from a knife rack on your left falls')
    sleep(3)
    print('It threatens to cut you in half')
    sleep(3)
    opt2 = input('Leap off the counter (w) or run forward (n) to avoid the falling knife')
    if opt2 == 'w':
        sleep(3)
        print('There is nothing to break your fall')
        sleep(3)
        print('You die from the impact of hitting the floor, game over!')
    elif opt2 == 'n':
        sleep(3)
        print('The falling knife just misses you and you feel the air brush over your back')
        sleep(3)
        print('Just above you is a bit of string used to hold birthday cards that stretches to the other side of the room, you could perhaps get closer to the serum')
        sleep(3)
        print('To your right is a paperclip and a post-it-note that you could easily fashion into a hang glider, this could also get you to the other side of the room')
        sleep(3)
        opt3 = input('Climb  up the spice rack to get to the string and tight-walk across the room (a) or fashion a hang glider to fly across (e)')
        if opt3 == 'a':
            sleep(3)
            print('You climb up the spice rack and step on to the string')
            sleep(3)
            print('You make it half way across the room when...')
            sleep(3)
            print('the string snaps and you are sent falling to your death, game over!')
        elif opt3 == 'e':
            sleep(3)
            print('After a few minutes of fiddling, you make a hang glider')
            sleep(3)
            print('You get in position, run to the edge of the counter and jump off')
            sleep(3)
            print('You\'re glider works, you fly over the dogs basket and past the bowl of fruit and finally land on the table where the serum is')
            sleep(3)
            print('After landing, you see the bottle of serum, but a bird has just flown in the window and landed on the table with you')
            sleep(3)
            print('It thinks you are a worm and wants to eat you')
            sleep(3)
            opt4 = input('Try and defend yourself with the paperclip from your glider (d) or run past the bird to the serum (r)')
            if opt4 == 'r':
                sleep(3)
                print('You begin to run past the bird for the serum')
                sleep(3)
                print('But the bird is too quick, picks you up in its beak and carries you to its nest to feed you to its babies, game over!')
            elif opt4 == 'd':
                sleep(3)
                print('You pull the paperclip out of your hang glider and the bird darts its beak towards you')
                sleep(3)
                print('Its beak just misses you as you move to the side')
                sleep(3)
                print('You stab the bird in the eye with the end of the paperclip and the bird calls out in pain')
                sleep(3)
                print('It flies away , leaving you with the serum, you take the cork off the bottle and start drinking')
                sleep(3)
                print('The effects of the serum courses through your veins, and you expand rapidly')
                sleep(3)
                print('Finally, you\'re back to normal size, you won!')
elif opt1 == 'w':
    sleep(3)
    print('You jump off the counter and land with a squelch')
    sleep(3)
    print('A mop has broken your fall')
    sleep(3)
    print('To your right is a mouse, ahead of you is your trusty dog, resting in his basket')
    sleep(3)
    opt2 = input('Go forward, past the dogs basket (n) or attempt to tame the mouse and ride it to the table with the serum on (t)')
    if opt2 == 'n':
        sleep(3)
        print('You move across the floor towards the table, when your dog takes a sudden, keen interest you')
        sleep(3)
        print('The dog licks his lips and sniffs the air in your direction')
        sleep(3)
        print('Thinking you are food, your dog darts towards you and eats you, game over!')
    elif opt2 == 't':
        sleep(3)
        print('You remove one of the fibres of the mop')
        sleep(3)
        print('You then use it to tie around the mouses neck, and jump on its back')
        sleep(3)
        print('At first the mouse struggles, but it subsides')
        sleep(3)
        print('You ride the mouse on its back straight to the table')
        sleep(3)
        print('You get off the mouse and now are faced with the task of getting up to the table')
        sleep(3)
        opt3 = input('You must either climb the curtains (c) or climb on one of the legs of the table using the fibre from the mop (l)')
        if opt3 == 'l':
            sleep(3)
            print('You throw the mop fibre around the table leg and begin to climb')
            sleep(3)
            print('The fibre is still damp and begins to slip')
            sleep(3)
            print('You fall to the floor on your head and fracture your skull, killing you, game over!')
        elif opt3 == 'c':
            sleep(3)
            print('You grab the folds of the curtains and begin to climb')
            sleep(3)
            print('You gradually make your way up, but you lose grip and one of your hands comes off')
            sleep(3)
            print('Throwing your hand up, you suddenly realise you have made it as your hand touches the edge of the table')
            sleep(3)
            print('Climbing up to the table, you now are presented with the bottle')
            sleep(3)
            print('You take the cork off the serum bottle and start drinking')
            sleep(3)
            print('The effects of the serum courses through your veins, and you expand rapidly')
            sleep(3)
            print('Finally, you\'re back to normal size, you won!')

